"""Validator for the countries API — generated by apitf-scaffold."""
from __future__ import annotations

from typing import Any

from apitf.validators.base_validator import BaseValidator, ValidationResult

REQUIRED_FIELDS: tuple[str, ...] = (
    "tld", "cca2", "ccn3", "cca3", "cioc", "independent", "status",
    "unMember", "idd", "capital", "altSpellings", "region", "subregion",
    "landlocked", "borders",
)


class CountriesValidator(BaseValidator):
    """Validates a single countries API response object."""

    def validate(self, data: Any) -> ValidationResult:
        for field in REQUIRED_FIELDS:
            if field not in data:
                self._fail(f"Missing required field: {field!r}")
            elif data[field] is None:
                self._fail(f"Field {field!r} must not be null")
        return self._pass()
