"""Validators for the JSONPlaceholder API — generated by apitf-scaffold, corrected manually.

JSONPlaceholder has 4 distinct resource types with different schemas.
One validator per resource type satisfies the BaseValidator contract.
"""
from __future__ import annotations

from typing import Any

from apitf.validators.base_validator import BaseValidator, ValidationResult

POST_REQUIRED_FIELDS: tuple[str, ...] = ("id", "userId", "title", "body")
COMMENT_REQUIRED_FIELDS: tuple[str, ...] = ("id", "postId", "name", "email", "body")
USER_REQUIRED_FIELDS: tuple[str, ...] = ("id", "name", "username", "email", "phone", "website")
TODO_REQUIRED_FIELDS: tuple[str, ...] = ("id", "userId", "title", "completed")
ALBUM_REQUIRED_FIELDS: tuple[str, ...] = ("id", "userId", "title")


class JsonplaceholderValidator(BaseValidator):
    """Validates a single /posts response object (the primary resource)."""

    def validate(self, data: Any) -> ValidationResult:
        for field in POST_REQUIRED_FIELDS:
            if field not in data:
                self._fail(f"Missing required field: {field!r}")
            elif data[field] is None:
                self._fail(f"Field {field!r} must not be null")
        return self._pass()


class CommentValidator(BaseValidator):
    """Validates a single /comments response object."""

    def validate(self, data: Any) -> ValidationResult:
        for field in COMMENT_REQUIRED_FIELDS:
            if field not in data:
                self._fail(f"Missing required field: {field!r}")
            elif data[field] is None:
                self._fail(f"Field {field!r} must not be null")
        return self._pass()


class UserValidator(BaseValidator):
    """Validates a single /users response object."""

    def validate(self, data: Any) -> ValidationResult:
        for field in USER_REQUIRED_FIELDS:
            if field not in data:
                self._fail(f"Missing required field: {field!r}")
            elif data[field] is None:
                self._fail(f"Field {field!r} must not be null")
        return self._pass()


class TodoValidator(BaseValidator):
    """Validates a single /todos response object."""

    def validate(self, data: Any) -> ValidationResult:
        for field in TODO_REQUIRED_FIELDS:
            if field not in data:
                self._fail(f"Missing required field: {field!r}")
            elif data[field] is None:
                self._fail(f"Field {field!r} must not be null")
        return self._pass()


class AlbumValidator(BaseValidator):
    """Validates a single /albums response object."""

    def validate(self, data: Any) -> ValidationResult:
        for field in ALBUM_REQUIRED_FIELDS:
            if field not in data:
                self._fail(f"Missing required field: {field!r}")
            elif data[field] is None:
                self._fail(f"Field {field!r} must not be null")
        return self._pass()
