"""
apitf CLI — entry points registered in pyproject.toml.

Commands
--------
apitf-parse  <spec_file> [--json]
    Parse a spec file (PDF, OpenAPI YAML/JSON, Markdown) and print the
    extracted EndpointSpec objects.  Use --json for machine-readable output.

apitf-scaffold <spec_file> --env <env_name> [--out <dir>]
    Parse the spec then emit three ready-to-use artefacts:
      1. YAML snippet  — paste into config/environments.yaml
      2. Validator stub — apitf/validators/<env>_validator.py
      3. Test stub     — tests/test_<env>.py
    Prints to stdout by default; --out writes files directly.
"""

from __future__ import annotations

import argparse
import json
import sys
import textwrap
from pathlib import Path


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _load_parser(source: Path):
    """Return the right BaseSpecParser subclass for *source*."""
    from apitf.spec_parser.pdf_parser import PDFParser
    from apitf.spec_parser.openapi_parser import OpenAPIParser
    from apitf.spec_parser.markdown_parser import MarkdownParser

    suffix = source.suffix.lower()
    if suffix in PDFParser.supported_extensions:
        return PDFParser()
    if suffix in OpenAPIParser.supported_extensions:
        return OpenAPIParser()
    if suffix in MarkdownParser.supported_extensions:
        return MarkdownParser()
    print(f"[apitf] Unsupported file type: {suffix}", file=sys.stderr)
    sys.exit(1)


def _specs_from(source: Path):
    parser = _load_parser(source)
    specs = parser.parse(source)
    if not specs:
        print(f"[apitf] No endpoints extracted from {source}", file=sys.stderr)
        sys.exit(1)
    return specs


# ---------------------------------------------------------------------------
# apitf-parse
# ---------------------------------------------------------------------------

def cmd_parse(argv: list[str] | None = None) -> None:
    """Entry point: apitf-parse"""
    p = argparse.ArgumentParser(
        prog="apitf-parse",
        description="Parse a spec file and print the extracted endpoints.",
    )
    p.add_argument("spec_file", type=Path, help="Path to spec file (.pdf, .yaml, .json, .md)")
    p.add_argument("--json", action="store_true", dest="as_json",
                   help="Emit machine-readable JSON (one object per line)")
    args = p.parse_args(argv)

    source = args.spec_file.resolve()
    if not source.exists():
        print(f"[apitf] File not found: {source}", file=sys.stderr)
        sys.exit(1)

    specs = _specs_from(source)

    if args.as_json:
        for s in specs:
            print(json.dumps({
                "env_name": s.env_name,
                "base_url": s.base_url,
                "path": s.path,
                "method": s.method,
                "response_fields": s.response_fields,
                "thresholds": s.thresholds,
                "description": s.description,
            }))
    else:
        print(f"\nExtracted {len(specs)} endpoint(s) from {source.name}\n")
        print(f"{'#':<4} {'METHOD':<8} {'PATH':<40} FIELDS")
        print("-" * 80)
        for i, s in enumerate(specs, 1):
            fields = ", ".join(s.response_fields[:5])
            if len(s.response_fields) > 5:
                fields += f" … (+{len(s.response_fields) - 5} more)"
            print(f"{i:<4} {s.method:<8} {s.path:<40} {fields}")
        print()
        print(f"Base URL : {specs[0].base_url}")
        print(f"Env name : {specs[0].env_name}")
        print()
        print("Next step:")
        print(f"  apitf-scaffold {source} --env {specs[0].env_name}")


# ---------------------------------------------------------------------------
# apitf-scaffold
# ---------------------------------------------------------------------------

_YAML_SNIPPET = """\
# ── Add this block to config/environments.yaml ──────────────────────────────
{env_name}:
  base_url: {base_url}
  probe_path: {probe_path}
  thresholds:
    max_response_time: 5   # seconds — adjust to your SLA
"""

_VALIDATOR_STUB = '''\
"""Validator for the {env_name} API — generated by apitf-scaffold."""
from __future__ import annotations

from typing import Any

from apitf.validators.base_validator import BaseValidator, ValidationResult

REQUIRED_FIELDS: tuple[str, ...] = ({fields_repr})


class {class_name}(BaseValidator):
    """Validates a single {env_name} API response object."""

    def validate(self, data: Any) -> ValidationResult:
        for field in REQUIRED_FIELDS:
            if field not in data:
                self._fail(f"Missing required field: {{field!r}}")
            elif data[field] is None:
                self._fail(f"Field {{field!r}} must not be null")
        return self._pass()
'''

_TEST_STUB = '''\
"""Tests for the {env_name} API — generated by apitf-scaffold.

Replace the TODO markers with real assertions against your spec contract.
Run with:  pytest --env {env_name} -v
"""
from __future__ import annotations

import allure
import pytest

from apitf.http_client import HttpClient
from apitf.validators.{module_name}_validator import {class_name}

pytestmark = [pytest.mark.{env_name}, allure.suite("{env_name}")]


@pytest.mark.equivalence
@pytest.mark.flaky(reruns=2, reruns_delay=2)
def test_{env_name}_positive_baseline(env_config):
    """Positive: probe_path returns 2xx within the configured threshold."""
    cfg = env_config["{env_name}"]
    with HttpClient(cfg["base_url"]) as client:
        resp = client.get(cfg["probe_path"])
    assert resp.status_code == 200, f"Expected 200, got {{resp.status_code}}"
    max_ms = cfg["thresholds"]["max_response_time"] * 1000
    assert resp.response_time_ms < max_ms, (
        f"SLA breach: {{resp.response_time_ms:.0f}}ms > {{max_ms:.0f}}ms"
    )


@pytest.mark.equivalence
@pytest.mark.flaky(reruns=2, reruns_delay=2)
def test_{env_name}_schema(env_config):
    """Schema: response matches the {class_name} contract."""
    cfg = env_config["{env_name}"]
    with HttpClient(cfg["base_url"]) as client:
        resp = client.get(cfg["probe_path"])
    assert resp.status_code == 200
    body = resp.json_body
    # If the endpoint returns a list, validate the first item
    item = body[0] if isinstance(body, list) else body
    result = {class_name}().validate(item)
    assert result.passed, result.errors


# TODO: add negative, boundary, performance, and state-based tests
# following the patterns in tests/test_countries.py and tests/test_weather.py
'''


def cmd_scaffold(argv: list[str] | None = None) -> None:
    """Entry point: apitf-scaffold"""
    p = argparse.ArgumentParser(
        prog="apitf-scaffold",
        description="Parse a spec and emit a YAML snippet, validator, and test stub.",
    )
    p.add_argument("spec_file", type=Path, help="Path to spec file")
    p.add_argument("--env", required=True, metavar="ENV_NAME",
                   help="Environment key to use (e.g. 'myapi')")
    p.add_argument("--out", type=Path, default=None, metavar="DIR",
                   help="Write files to DIR instead of printing to stdout")
    args = p.parse_args(argv)

    source = args.spec_file.resolve()
    if not source.exists():
        print(f"[apitf] File not found: {source}", file=sys.stderr)
        sys.exit(1)

    env = args.env
    specs = _specs_from(source)

    # Derive names
    class_name = "".join(w.title() for w in env.replace("-", "_").split("_")) + "Validator"
    module_name = env.replace("-", "_")
    base_url = specs[0].base_url
    probe_path = specs[0].path if specs else "/"
    all_fields = []
    for s in specs:
        for f in s.response_fields:
            if f not in all_fields:
                all_fields.append(f)
    fields_repr = ", ".join(f'"{f}"' for f in all_fields[:10])
    if all_fields:
        fields_repr += ","  # trailing comma for tuple

    yaml_block = _YAML_SNIPPET.format(
        env_name=env, base_url=base_url, probe_path=probe_path,
    )
    validator_src = _VALIDATOR_STUB.format(
        env_name=env, class_name=class_name, fields_repr=fields_repr,
    )
    test_src = _TEST_STUB.format(
        env_name=env, class_name=class_name, module_name=module_name,
    )

    if args.out:
        out = args.out.resolve()
        out.mkdir(parents=True, exist_ok=True)

        val_path = out / f"{module_name}_validator.py"
        test_path = out / f"test_{module_name}.py"
        yaml_path = out / f"{env}_yaml_snippet.txt"

        val_path.write_text(validator_src, encoding="utf-8")
        test_path.write_text(test_src, encoding="utf-8")
        yaml_path.write_text(yaml_block, encoding="utf-8")

        print(f"[apitf] Written to {out}/")
        print(f"  {val_path.name}  →  copy to apitf/validators/")
        print(f"  {test_path.name}  →  copy to tests/")
        print(f"  {yaml_path.name}  →  paste into config/environments.yaml")
    else:
        _section("1. Paste into config/environments.yaml", yaml_block)
        _section(f"2. Save as apitf/validators/{module_name}_validator.py", validator_src)
        _section(f"3. Save as tests/test_{module_name}.py", test_src)
        print("Then run:  pytest --env", env, "-v")


def _section(title: str, body: str) -> None:
    bar = "─" * 70
    print(f"\n{bar}")
    print(f"  {title}")
    print(bar)
    print(textwrap.indent(body.strip(), "  "))
    print()
